const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("\n🚀 Deploying CampusAchievement to Base Sepolia...");

  const [deployer] = await ethers.getSigners();

  if (!deployer) {
    console.error("❌ No deployer account found!");
    console.error("   Make sure DEPLOYER_PRIVATE_KEY is set in .env.local");
    process.exit(1);
  }

  console.log("📬 Deployer address:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("💰 Deployer balance:", ethers.formatEther(balance), "ETH");

  if (balance === 0n) {
    console.warn("⚠️  Warning: Deployer has zero balance. You may need test ETH.");
  }

  console.log("\nCompiling and deploying...");

  const CampusAchievement = await ethers.getContractFactory("CampusAchievement");
  const contract = await CampusAchievement.deploy(deployer.address);

  await contract.waitForDeployment();
  const contractAddress = await contract.getAddress();

  console.log("\n✅ CampusAchievement deployed successfully!");
  console.log("📍 Contract Address:", contractAddress);
  console.log("🔗 BaseScan:", `https://sepolia.basescan.org/address/${contractAddress}`);

  // Write config
  const configPath = path.join(__dirname, "../src/config/contract.js");
  const artifactPath = path.join(__dirname, "../artifacts/contracts/CampusAchievement.sol/CampusAchievement.json");

  const abi = JSON.parse(fs.readFileSync(artifactPath)).abi;

  const configContent = `// AUTO-GENERATED by scripts/deploy.cjs — DO NOT EDIT MANUALLY
// Deployed on: ${new Date().toISOString()}

export const CONTRACT_ADDRESS = "${contractAddress}";
export const DEPLOYER_ADDRESS = "${deployer.address}";
export const CHAIN_ID = 84532;
export const NETWORK_NAME = "Base Sepolia";
export const EXPLORER_URL = "https://sepolia.basescan.org";

export const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)};
`;

  fs.writeFileSync(configPath, configContent);
  console.log("\n📝 Contract config updated → src/config/contract.js");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n❌ Deployment failed:");
    console.error(error);
    process.exit(1);
  });